name: Brimark API Publish

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore Dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
    - name: Publish
      run: dotnet publish --configuration Release --output ./publish --runtime linux-x64 -p:PublishTrimmed=true
    - name: FTP Deployment
      uses: airvzxf/ftp-deployment-action@latest
      with:
        server: connieprice.co.uk
        user: brimark-api
        password: ${{ secrets.ftp_password }}
        local_dir: /home/runner/work/brimark-backend/brimark-backend/publish/
