name: Brimark API Publish

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore Dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
    - name: Publish
      run: dotnet publish --configuration Release --output ./publish --runtime linux-x64 --self-contained false -p:PublishTrimmed=true
    - name: FTP
      uses: MajorVengeance/Ftp-Deploy-Action@v0.2.3-alpha
      with:
        ftp_host: connieprice.co.uk
        ftp_username: brimark-api
        ftp_password: ${{ secrets.ftp_password }}
        local_source_dir: /home/runner/work/brimark-backend/brimark-backend/publish/
